export const GET_ALL_LEADS_REQUEST = 'GET_ALL_LEADS_REQUEST';
export const GET_ALL_LEADS_SUCCESS = 'GET_ALL_LEADS_SUCCESS';
export const GET_ALL_LEADS_FAILED = 'GET_ALL_LEADS_FAILED';

export const UPDATE_LEAD_STATUS_REQUEST = 'UPDATE_LEAD_STATUS_REQUEST';
export const UPDATE_LEAD_STATUS_SUCCESS = 'UPDATE_LEAD_STATUS_SUCCESS';
export const UPDATE_LEAD_STATUS_FAILED = 'UPDATE_LEAD_STATUS_FAILED';