version: '3.4'

services:
  leadmanagement.api:
    image: ${DOCKER_REGISTRY-}leadmanagementapi
    build:
      context: .
      dockerfile: LeadManagement.Api/Dockerfile
    ports:
      - "8090:80"
      - "8091:443"
  
  client:
    container_name: client
    build:
      context: .
      dockerfile: leadmanagement.client/Dockerfile
    volumes:
      - './leadmanagement.client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true