version: '3.4'

services:
  leadmanagement.api:
    image: ${DOCKER_REGISTRY-}leadmanagementapi
    build:
      context: .
      dockerfile: LeadManagement.Api/Dockerfile
    ports:
      - "8090:80"
      - "8091:443"
    depends_on:
      - leadmanagement.mysql
    networks:
      - leadmanagement.network

  leadmanagement.mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - leadmanagement.network

networks:
  leadmanagement.network:
    driver: bridge